spring:
  application:
    name: finnplay
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE
#    username: $MYSQLDB_USER
#    password: $MYSQLDB_ROOT_PASSWORD
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa:
    open-in-view: false
server:
  error:
    include-exception: true
    include-message: always
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect